'use client';
import Image from 'next/image';
import {useRef,useState} from 'react';
import type {BoardItem,Frame} from '@/data/boards';
export function FrameImage({image,alt,label,priority=false}:{image:string;alt:string;label:string;priority?:boolean}){const[failed,setFailed]=useState(false);return image&&!failed?<Image src={image} alt={alt} fill priority={priority} sizes="(max-width: 650px) 100vw, (max-width: 1000px) 50vw, 40vw" onError={()=>setFailed(true)}/>:<span className="empty-frame" role="img" aria-label={`Photo placeholder: ${label}`}><span className="frame-plus" aria-hidden="true">+</span><span className="frame-hint">Your photo here</span></span>}
export function Tile({item,children}:{item:BoardItem;children?:React.ReactNode}){const modal=useRef<HTMLDialogElement>(null);return <article className={`tile ${item.tone} ${item.size||''} ${item.image?'has-image':'has-frame'} tile-${item.id}`}><button className="tile-button" onClick={()=>modal.current?.showModal()} aria-label={`Open ${item.title}`}><span className="tile-media"><FrameImage image={item.image} alt={item.alt} label={item.title.replace(/\.$/,'')}/></span><span className="tile-caption">{item.kicker&&<span className="eyebrow">{item.kicker}</span>}<strong>{item.title}</strong></span>{item.stat&&<span className="tile-stat">{item.stat}<small>Elo</small></span>}<span className="tile-arrow" aria-hidden="true">↗</span></button><dialog ref={modal} className={`detail-dialog ${item.tone}`} aria-label={item.title} onClick={e=>{if(e.target===e.currentTarget)modal.current?.close()}}><button className="close-dialog" autoFocus onClick={()=>modal.current?.close()} aria-label="Close details">×</button><div className="detail-media"><FrameImage image={item.image} alt={item.alt} label={item.title}/></div><div className="detail-copy">{item.kicker&&<span className="eyebrow">{item.kicker}</span>}<h2>{item.title}</h2>{item.detail&&<p>{item.detail}</p>}{item.credit&&<a className="credit" href={item.credit.url} target="_blank" rel="noopener noreferrer">Source: {item.credit.title} ↗</a>}{item.credit?.licenseUrl&&<a className="frame-credit" href={item.credit.licenseUrl} target="_blank" rel="noopener noreferrer">Photo license ↗</a>}{children}</div>{item.frames&&<div className="extra-frames">{item.frames.map((f:Frame)=><figure key={f.label}><div className="extra-image"><FrameImage {...f}/></div><figcaption>{f.label}{f.credit&&<a className="frame-credit" href={f.credit.url} target="_blank" rel="noopener noreferrer">{f.credit.title} ↗</a>}</figcaption></figure>)}</div>}</dialog></article>}
export function AboutButton({children}:{children:React.ReactNode}){const dialog=useRef<HTMLDialogElement>(null);return <><button className="about-button" onClick={()=>dialog.current?.showModal()}>A little about me <span>↗</span></button><dialog id="about-jibran" ref={dialog} className="about-dialog lavender" aria-label="About Jibran" onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close()}}><button className="close-dialog" autoFocus aria-label="Close about" onClick={()=>dialog.current?.close()}>×</button>{children}</dialog></>}

export function AboutPortrait({children}:{children:React.ReactNode}){return <button type="button" className="cover-portrait" aria-label="A little about me — open my background" aria-haspopup="dialog" aria-controls="about-jibran" onClick={()=>{const dialog=document.getElementById("about-jibran");if(dialog instanceof HTMLDialogElement)dialog.showModal();}}>{children}</button>}
